"""add incident_report_subjects table

Revision ID: 315245194618
Revises: 537a91827de7
Create Date: 2026-02-12 07:50:26.634843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '315245194618'
down_revision: Union[str, None] = '537a91827de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_report_subjects',
    sa.Column('incident_report_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('RESPONSIBLE', 'INVOLVED', 'WITNESS', name='subjectrole'), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_report_id'], ['incident_reports.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_report_subjects')
    # ### end Alembic commands ###
