"""add incident_reports table

Revision ID: 537a91827de7
Revises: 578d61df31cf
Create Date: 2026-02-12 04:18:38.293331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '537a91827de7'
down_revision: Union[str, None] = '578d61df31cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_reports',
    sa.Column('incident_type_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'UNDER_REVIEW', 'CONFIRMED', 'FALSE_ALARM', 'CONTAINED', 'MITIGATION_IN_PROGRESS', 'RESOLVED', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('escalation_level', sa.Enum('NONE', 'MONITORING', 'ESCALATED', 'EMERGENCY_STATE_DECLARED', name='escalationlevel'), nullable=False),
    sa.Column('reported_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.uid'], ),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_reports')
    # ### end Alembic commands ###
