"""add plant_states table

Revision ID: b0aa6c40fefe
Revises: 315245194618
Create Date: 2026-09-09 00:11:23.665325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b0aa6c40fefe'
down_revision: Union[str, None] = '315245194618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_states',
    sa.Column('tick', sa.BigInteger(), nullable=False),
    sa.Column('true_reactor_power', sa.Float(), nullable=False),
    sa.Column('true_core_temperature', sa.Float(), nullable=False),
    sa.Column('true_reactivity', sa.Float(), nullable=False),
    sa.Column('true_coolant_flow_rate', sa.Float(), nullable=False),
    sa.Column('true_coolant_pressure', sa.Float(), nullable=False),
    sa.Column('true_radiation_level', sa.Float(), nullable=False),
    sa.Column('true_containment_integrity', sa.Float(), nullable=False),
    sa.Column('measured_reactor_power', sa.Float(), nullable=False),
    sa.Column('measured_core_temperature', sa.Float(), nullable=False),
    sa.Column('measured_reactivity', sa.Float(), nullable=False),
    sa.Column('measured_coolant_flow_rate', sa.Float(), nullable=False),
    sa.Column('measured_coolant_pressure', sa.Float(), nullable=False),
    sa.Column('measured_radiation_level', sa.Float(), nullable=False),
    sa.Column('measured_containment_integrity', sa.Float(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_states')
    # ### end Alembic commands ###
